name: CI

# trigger for the execution of workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v2
        with:
          node-version: $({matrix.node-version})
          cache: 'npm'
      - run: ci
      - run: npm test
